#!/bin/bash
#SBATCH --job-name="Aro_L_{System_Name}"
#SBATCH --output="job.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -t 48:00:00
#SBATCH -A csd467
module load lammps
cd /oasis/scratch/comet/seroot/temp_project/Aromodel/{System_Name}
export OMP_NUM_THREADS=1

ibrun -np 24 lammps < in.init_{System_Name} > log.init_{System_Name}

