#!/bin/bash
#SBATCH --job-name="Aro_{name}"
#SBATCH --output="job.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -t 48:00:00
#SBATCH -A csd467
module load lammps
cd {Comet_Path}
export OMP_NUM_THREADS=1

{Orca_Path} {name}.inp > {name}.out

